name: Testworkflow

on: push

jobs: 
  TheMainJob: 
    name: RunningOnUbuntu
    runs-on: ubuntu-latest
    steps: 
      - name: RunningV2
        uses: actions/checkout@v2

      - name: RunningLinterSuper
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
