name: Testworkflow

on: push

jobs: 
  TheMainJob: 
    name: RunningOnUbuntu
    runs-on: ubuntu-latest
    steps: 
      - name: RunningV2
        uses: action/checkout@v2

      - name: RunningLinterSuper
       uses: github/super-linter@v3
       env:
         DEFAULT_BRNACH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
       
      
